#8 Added unit tests with 2 example tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,12 +10,30 @@ on:
     schedule:
         - cron: "0 0 * * 1-5"
 
+permissions:
+    checks: write
+
 jobs:
     build:
         runs-on: ubuntu-latest
 
         steps:
             - uses: actions/checkout@v4
+
+            - name: Build and Run Tests
+              run: |
+                mkdir app/build-unit-test && cd app/build-unit-test
+                cmake .. -DCMAKE_BUILD_TYPE=Debug
+                make all -j$(nproc)
+                ctest
+                cd ../../
+
+            - name: Publish Test Report
+              uses: mikepenz/action-junit-report@v4
+              if: success() || failure() # always run even if the previous step fails
+              with:
+                commit: ${{github.event.workflow_run.head_sha}}
+                report_paths: 'app/build-unit-test/results_*.xml'
 
             - name: Install toolchain, Doxygen & cppcheck
               run: |
